motiwari/BanditPAM

src/kmedoids_ucb.cpp, src/main.cpp
Added the log file's name as a parameter to the executable so that the user can specify it.
Test Cases (all function properly by outputting correct medoid list):
1. ./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1
2. ./BanditPAM -f ../../data/MNIST-1k.csv -n KMedoidsLogfile -k 10 -v 1
3. ./BanditPAM -f ../../data/MNIST-1k.csv -n KMedoidsLogfileNewName -k 10 -v 1
=> Logfile Parameter In CPP Binary

README.md, src/kmeds_pywrapper.cpp, tests/test_commit.py, tests/test_push.py
As per the description in Issue #38, the term `final_medoids` can confusing and counterintuitive. Since it's unlikely anyone will use `build_medoids`, we have decided to rename `final_medoids` to `medoids`. This task has been accomplished by modifying the Python wrapper as well as the corresponding test files. The README has also been updated to reflect the change in the name of the `KMedoids` attribute to `medoids`. The command `./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1 ` was run to ensure that the renaming process did not alter the program functionality, and indeed the proper set of medoids (`Medoids: 694,800,306,714,324,959,737,527,168,251`) were outputted.
=> Rename 'final_medoids' Attribute of KMedoids to 'medoids'

headers/kmedoids_ucb.hpp, src/kmedoids_ucb.cpp
The original code assigns the transposed input data to a variable called `data` in `fit_naive()` and `fit_bpam()` and uses it as a global variable for all called functions like `build_naive(), swap_naive(), build(), swap()`. The dependence of the functions is as follows 
```
1. KMedoids::fit_naive() 
|- KMedoids::build_naive()
|- KMedoids::lossFn()
|- KMedoids::swap_naive()
|- KMedoids::lossFn()
2. KMedoids::fit_bpam()
|- KMedoids::build()
|- KMedoids::build_sigma()
|- KMedoids::lossFn()
|- KMedoids::build_target()
|- KMedoids::lossFn()
|- KMedoids::swap()
|- KMedoids::calc_best_distances_swap()
|- KMedoids::lossFn()
|- KMedoids::swap_sigma()
|- KMedoids::lossFn()
|- KMedoids::swap_target() 
|- KMedoids::lossFn()
3. KMedoids::calc_loss()
|- KMedoids::lossFn()
```
where the `lossFn()` …
=> Remove global variables. Fixes #31

src/main.cpp
Added back the missing argument `n` to the `getopt` function. The following is an example of renaming the log file in the output:
```
./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1 -n BanditPAM_log_file
```
We get the expected results with log file named `BanditPAM_log_file` as output:
```
Medoids: 694,800,306,714,324,959,737,527,168,251
```
=> Add argument n for logfile name. Fixes #54

README.md
To make instruction of installing `carma` more explicit, we add the change of directory command `cd headers/carma` from the repo's top-level directory before running the installation commands.
=> make the carma installation command more explicit. Fixes #34

README.md, headers/kmedoids_ucb.hpp, src/kmedoids_ucb.cpp, src/kmeds_pywrapper.cpp, src/main.cpp
The argument `k` in Python fit method is redundant since we have already specified the medoids number when we instantiate the `KMedoids` class. We therefore remove this argument in `fitPython()` method in `KMedsWrapper` class. The Python examples in repo are tested again using the updated code and the results are as follow:
The standard cases `./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1` with different loss functions `manhattan, cos, inf, L15` are also tested and they all give the expected results.
=> remove redundant medoids number k in Python fit method. Fixes #48

src/kmeds_pywrapper.cpp
Add version attribute in pybind module `PYBIND11_MODULE(BanditPAM, m)` for the version of python package. The version number follows the value of `__version__` in `setup.py` file. 
The current version of this package is 
The update follows an example for version attribute from pybind doc: https://github.com/pybind/python_example/blob/master/src/main.cpp
The following 2 lines are used to covert a macro argument `VERSION_INFO` to a string constant:
```
#define STRINGIFY(x) #x
#define MACRO_STRINGIFY(x) STRINGIFY(x)
```
and here is the reference: https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html#Stringizing
=> add version attribute to python module. Fixes #63

src/main.cpp
Remove the loss parsing part in `main.cpp`. This part is handled in `setLossFn()` function in `kmedoids_ucb.cpp` so we don't need to duplicate it in `main`:
https://github.com/ThrunGroup/BanditPAM/blob/c5f9760e7c4a59b9381119545897adcd6516f06a/src/kmedoids_ucb.cpp#L111-L114
I have tested  all the cases and got the expected results:
```
(base) thomascheung@Thomass-MacBook-Pro src % ./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1 -l cos
Medoids: 567,182,839,340,385,979,915,758,609,649
(base) thomascheung@Thomass-MacBook-Pro src % ./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1       
Medoids: 694,800,306,714,324,959,737,527,168,251
(base) thomascheung@Thomass-MacBook-Pro src % ./BanditPAM -f ../../data/MNIST-1k.csv -k 10 -v 1 -l L15
Medoids: 194,319,558,60,133,896,448,475,251,354
(base) …
```
=> remove duplicated code on loss in main. Fixes #60

headers/kmedoids_ucb.hpp, src/kmedoids_ucb.cpp
I have filled in all the fields of the log file for the `naive` algorithm and tested it using the same example in issue #53  
The corresponding log file is
```
Built:891,392,354,714,23,805,527,777,251,972
Swapped:694,168,306,714,324,959,527,800,251,737
Num Swaps: 10
Final Loss: 7.44375
Build Logstring:
:compute_exactly
0: 1000
1: 1000
2: 1000
3: 1000
4: 1000
5: 1000
6: 1000
7: 1000
8: 1000
9: 1000
:loss
0: 8.97142
1: 8.64027
2: 8.40195
3: 8.21948
4: 8.05052
5: 7.91262
6: 7.80759
7: 7.7083
8: 7.6153
9: 7.54378
:p
0: 1e-06
1: 1e-06
2: 1e-06
3: 1e-06
4: 1e-06
5: 1e-06
6: 1e-06
7: 1e-06
8: 1e-06
9: 1e-06
:sigma
0: min: 0.489725, 25th: 1.01001, median: 1.16105, 75th: 1.37448, max: 2.18534, mean: 1.21614
1: min: 0, 25th: 0.349766, median: 0.474787, 75th: 0.625075, max: 1.74228, mean: 0.524651 …
```
=> complete the logfile for naive algorithm. Fixes #53

setup.py
This PR makes several changes to `setup.py` to ensure it is run correctly on OSX, Ubuntu, and other Linux distros:
- Modifying the `include_dirs` based on OS
- Modifying the necessary `libraries` based on OS
- Checking for the necessary dependencies on each platform
- Modifying the compiler flags based on OS
=> Modifying `setup.py` to be specific to OSX, Ubuntu, and other Linux distros

env_setup.sh, scripts/hook.sh, scripts/install-hooks.sh, scripts/template_hook.sh
Please review the Pull request for issue #13.  Updating scripts (env_setup.sh) to avoid re-running things that don't need to be re-run. 
- Modified the file `env_setup.sh`  to check the below two items:
1) If docker image `banditpam/cpp:latest` already exists, skip the creation of docker image
2) If pre-commit and pre-push hooks already exists, skip the creation of hooks
- Modified the file `scripts/install-hooks.sh` to fix the error in 'sed' command.
- Below tests are executed to validate above items
1) Ran the `env_setup.sh` when docker image does not exists 
2) Ran the `env_setup.sh` when docker image already exists 
3) Ran the `env_setup.sh` when `pre-commit` and `pre-push` hooks do not exist
4) Ran the ` env_setup.sh` when `pre-commit` and `pre-push` hooks already exist
- Modified …
=> Updating scripts to avoid re-running things that don't need to be re-run. Fix for issue #13

src/CMakeLists.txt, src/kmedoids_ucb.cpp
I have modified the naive algorithm to PAM. The logic of `swap_naive`  is changed so that the best and second best distance of each datapoint are cached and used in the computing the cost. When we swap medoid m_k with non-medoid x_i, the cost for datapoint x_j is computed as
1. if x_j is assigned to medoid m_k: cost = min(dist(x_i, x_j), second best distance of j)
2. if x_j is not assigned to medoid m_k: cost = min(dist(x_i, x_j), best distance of j)
Hence, the complexity of PAM is O(kn^2) . The algorithms are tested on the MNIST-1k data as follows:
`Original naive algorithm`
`PAM algorithm`
=> Modify naive algorithm to PAM. Fixes #1

src/kmedoids_ucb.cpp
This is the fix for issue #21.
- Modified the file `kmedoids_ucb.cpp` and added the method `signal_callback_handler`  for signal handling. 
- If CPP code is being executed and code gets the `ctrl+c` signal, it will execute this method to terminate the running process.
- This code is only handle the `ctrl+c` event when CPP code is running. I noticed that in the test cases we are reading large csv files in python code and it takes a while to finish that execution. This code does not handle that situation.
- Test case : If I am executing the test cases or any other examples and CPP code is taking a long time, if i give `ctrl+c` my process gets killed immediately with the message `^CCaught signal 2`
=> Updated the cpp code to catch the ctrl_c interruption. Fix for issue #21.

Dockerfile
This is the fix for issue #12.
To execute the `env_setup.sh` successfully, local instance of Docker must be installed and running
- Updated the code for checking out specific commit of `carma` : from `git checkout unstable` to `git checkout 502ab50`. That's the commit version currently working properly with BanditPAM.
- Added the below code to fix the SSL error in the execution of `env_setup.sh`
`yum -y install git-all` 
`export PATH=/usr/local/libexec/git-core:$PATH`
- After making these changes I can execute `env_setup.sh` successfully.
BanditPAM % docker images                       
REPOSITORY      TAG       IMAGE ID       CREATED              SIZE
banditpam/cpp   latest    03d9521c9f7b   About a minute ago   3.5GB
=> Updating the `Dockerfile` to fix the error in `env_setup.sh` execution

src/main.cpp
Updated the error message when the file is not passed/ not found. For instance, if the input file path is invalid, the program will give an error message as shown in the example below:
```
(base) thomascheung@Thomass-MacBook-Pro src % ./BanditPAM -f ../../data/MNIST-2k.csv -k 2 -v 1 
error: The file does not exist
```
=> Give informative error message if no file is passed. Fixes #85

headers/fastpam1.hpp, headers/kmedoids_algorithm.hpp, setup.py, src/CMakeLists.txt, src/fastpam1.cpp, src/kmedoids_algorithm.cpp, src/kmedoids_pywrapper.cpp, src/main.cpp
I have implemented `FastPAM1` algorithm in this commit. The `FastPAM1` algorithm follows from Algorithm 3 of the PAM and FastPAM1 paper https://arxiv.org/pdf/1810.05691.pdf, where the core idea is to replace the iteration of `k` medoids in the `swap` step with an if conditional outside the loop. This is achievable by using an array to compute `k` loss changes which results in O(N^2) per iteration. 
The algorithm is tested against MNIST-1k dataset as shown below.
It gives the expected set of medoids and the order of `k` is close of zero.
=> Implement FastPAM1. Fixes #106

src/kmedoids_algorithm.cpp, src/kmedoids_pywrapper.cpp, src/pam.cpp
I have fixed the following:
- Logic change: whenever there is a change in `algorithm` through `setter`, it is checked right after the `setter` so we don't need to do it in `fit` which is the original reason for the `checkAlgorithm()` to be there. 
- Add optional argument for `algorithm` in Python code. We can now change the algorithm like in the following example:
- Make the global variables explicit by using `this->` pointer function.
=> Make global variable explicit and add optional argument for algorithm

headers/banditpam.hpp, headers/fastpam1.hpp, headers/kmedoids_algorithm.hpp, headers/pam.hpp, src/banditpam.cpp, src/kmedoids_algorithm.cpp, src/kmedoids_pywrapper.cpp, src/main.cpp, src/pam.cpp
I have added headers `banditpam.hpp` and `pam.hpp` for `banditpam.cpp` and `pam.cpp` respectively. The format of the header follows from the `fastpam.hpp` header I have created in the previous PR #112. The updated code is tested on Python using MNIST-1k as the dataset, all algorithms give expected results.
=> Create headers for banditpam.cpp and pam.cpp

scripts/readme_ex2.py
For some reason, the order of imports matters; likely because some import has a side effect
=> Updating readme_ex2.py to avoid segfault

MANIFEST.in, setup.py
Contains a hotfix for #170 and some Google Colab bugs.
For Paperspace Gradient:
- allows users to install `banditpam==3.0.1` on Paperspace Gradient instances by installing the necessary dependencies and `armadillo 10.8` automatically in `setup.py`
- Builds a recent (`>=10.8`) armadillo from source
For Google Colab:
- Installs the necessary Ubuntu dependencies
- Fixes a missing space that was conjoining the repo name with the local installation path
- Replaces the `MANIFEST.in` so the `headers` are properly included in the source distribution
Note: On Google Colab, the installed `cmake` is only `3.12`, so we do NOT build `armadillo` from source as doing so would require building a newer version of `cmake`, which takes way too long. Instead, we keep the current workaround of building the …
=> Hotfix: fixing installation on paperspace gradient

.gitignore, headers/algorithms/kmedoids_algorithm.hpp, headers/python_bindings/kmedoids_pywrapper.hpp, setup.py, src/algorithms/banditpam.cpp, src/algorithms/fastpam1.cpp, src/algorithms/kmedoids_algorithm.cpp, src/algorithms/pam.cpp, src/python_bindings/build_medoids_python.cpp, src/python_bindings/fit_python.cpp, src/python_bindings/kmedoids_pywrapper.cpp, src/python_bindings/labels_python.cpp, src/python_bindings/loss_python.cpp, src/python_bindings/medoids_python.cpp, src/python_bindings/steps_python.cpp, tests/test_smaller.py, tests/utils.py
BanditPAM `v3.0.2` contains several bugfixes:
**Organization and Functionality:**
- We now allow the user to set a `seed` for reproducible results (must be called with `banditpam.set_num_threads(1)` for deterministic reproducibility) (Fixes #176)
- We have added the `KMedoids.average_loss` attribute to contain the final average clustering loss after fitting (Fixes #174)
- We throw an `std::invalid_argument` error properly when specifying an invalid loss function (Fixes #173, Fixes #141)
**Tests:**
- We now also test `PAM` in `tests/test_smaller.py`
**Style:**
- We change `PAM` and `FastPAM1` to use `this->*lossFn` instead of `KMedoids::cachedLoss` to avoid resetting the cache for them; they do not benefit much from a cache anyway
- Nits
**Documentation:**
- Created documentation for new …
=> BanditPAM `v3.0.2`

.github/workflows/build_linux_wheels.yml, .github/workflows/build_mac_wheels.yml, .github/workflows/run_cmake_build.yml, .github/workflows/run_linux_tests.yml, .github/workflows/run_style_checks.yml, .github/workflows/run_windows_tests.yml, CMakeLists.txt, README.md, docs/install_linux.md, docs/install_mac.md, docs/install_windows.md, docs/long_desc.rst, headers/algorithms/kmedoids_algorithm.hpp, pyproject.toml, scripts/colab_files/colab_setup.sh, setup.py, src/CMakeLists.txt, src/algorithms/banditpam.cpp, src/algorithms/banditpam_orig.cpp, src/main.cpp, src/python_bindings/kmedoids_pywrapper.cpp
BanditPAM `v4.0.1` contains a few minor changes:
**Organization and Functionality:**
- Makes  `cibuildwheel` more verbose
- For CMake builds, checks out the current branch (not `main`) in GHA
- Changes the CMake build to `Release` mode to avoid running sanitizers in GHA
- Adds status badges (Fixes #224)
- Fixes the GHA builds by including the proper directory for `armadillo` (the locally installed version)
**Tests:**
No changes.
**Style:**
No changes.
**Documentation:**
- Updates `README.md` and other docs
=> BanditPAM `v4.0.1`

.github/workflows/linux_build_wheels.yml, .github/workflows/linux_run_tests.yml, .github/workflows/mac_arm64_cmake_build.yml, .github/workflows/mac_arm64_run_tests.yml, .github/workflows/mac_build_wheels.yml, .github/workflows/mac_intel_cmake_build.yml, .github/workflows/mac_intel_run_tests.yml, .github/workflows/run_style_checks.yml, .github/workflows/run_windows_tests.yml, setup.py
BanditPAM v5.0.0 contains several major changes:
**Organization and Functionality:**
- Updates all GHA dependencies
- Fixes all GHA on Linux and Mac, including source C++ builds, local builds, and wheel builds
- Updates supported Python versions to Python 3.10 - 3.13  
- Separates GHA by platform
- Forces LLVM's `clang` usage on Mac for compilation
- Updates `setup.py`
**Tests:**
No changes.
**Style:**
No changes.
**Documentation:**
No Changes.
=> BanditPAM 5.0.0: Fixing all github actions and shipping new wheels

.github/workflows/mac_arm64_run_tests.yml, .github/workflows/mac_build_wheels.yml, .github/workflows/run_style_checks.yml, pyproject.toml, setup.py, src/algorithms/banditpam.cpp, src/algorithms/banditpam_orig.cpp
The previous release, v5.0.0, contained several bugs.
This PR:
- Gets all GHA to work correctly
- Cleans up a lot of unnecessary things in the builds
- Updates `carma` and all the GHA
- Updates the supported python versions
=> BanditPAM v5.0.1

.github/workflows/mac_build_wheels.yml, pyproject.toml, readme_ex1.py, scripts/docker/cibw_before_all_macos.sh, setup.py
BanditPAM `v.6.0.1` fixes the previously broken BanditPAM `v.5.0.0` by:
- Updating the Mac wheels to be built on an m1 `macos-latest` instead of an intel `macos-13`
- Statically linking OpenMP
=> Fixing GHA again
